global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Aplicação rodando em container Docker
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8081']
        labels:
          application: 'kafka-consumer-demo'
          environment: 'docker'

  # Aplicação rodando no host (desenvolvimento local)
  - job_name: 'spring-boot-app-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'kafka-consumer-demo'
          environment: 'local'
